Pod::Spec.new do |s|
  s.name     = "PredictionService"
  s.version  = "1.0.0"
  s.license  = "Apache License, Version 2.0"
  s.authors  = { 'gRPC contributors' => 'grpc-io@googlegroups.com' }
  s.homepage = "https://grpc.io/"
  s.summary = "Using tensorflow serving in an ios application"
  s.source = { :git => 'https://github.com/grpc/grpc.git' }

  s.ios.deployment_target = "7.1"
  s.osx.deployment_target = "10.9"

  # Base directory where the .proto files are.
  # src = "../../protos"
  src = "../../../../../tensorflow"

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0"

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = 'Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  # Directory where the generated files will be placed.
  dir = "#{pods_root}/#{s.name}"

  s.prepare_command = <<-CMD
    mkdir -p #{dir}
    #{protoc} \
        --plugin=protoc-gen-grpc=#{plugin} \
        --objc_out=#{dir} \
        --grpc_out=#{dir} \
        -I #{src} \
        -I #{protoc_dir} \
	#{src}/tensorflow_serving/apis/input.proto \
	#{src}/tensorflow_serving/apis/regression.proto \
	#{src}/tensorflow_serving/apis/predict.proto \
	#{src}/tensorflow_serving/apis/prediction_service.proto \
	#{src}/tensorflow_serving/apis/get_model_metadata.proto \
	#{src}/tensorflow_serving/apis/inference.proto \
	#{src}/tensorflow_serving/apis/model.proto \
	#{src}/tensorflow_serving/apis/classification.proto \
	#{src}/tensorflow/core/util/test_log.proto \
	#{src}/tensorflow/core/util/memmapped_file_system.proto \
	#{src}/tensorflow/core/util/saved_tensor_slice.proto \
	#{src}/tensorflow/core/util/event.proto \
	#{src}/tensorflow/core/framework/graph.proto \
	#{src}/tensorflow/core/framework/step_stats.proto \
	#{src}/tensorflow/core/framework/tensor_shape.proto \
	#{src}/tensorflow/core/framework/function.proto \
	#{src}/tensorflow/core/framework/graph_transfer_info.proto \
	#{src}/tensorflow/core/framework/variable.proto \
	#{src}/tensorflow/core/framework/summary.proto \
	#{src}/tensorflow/core/framework/types.proto \
	#{src}/tensorflow/core/framework/tensor_slice.proto \
	#{src}/tensorflow/core/framework/log_memory.proto \
	#{src}/tensorflow/core/framework/cost_graph.proto \
	#{src}/tensorflow/core/framework/versions.proto \
	#{src}/tensorflow/core/framework/attr_value.proto \
	#{src}/tensorflow/core/framework/remote_fused_graph_execute_info.proto \
	#{src}/tensorflow/core/framework/op_def.proto \
	#{src}/tensorflow/core/framework/node_def.proto \
	#{src}/tensorflow/core/framework/kernel_def.proto \
	#{src}/tensorflow/core/framework/tensor_description.proto \
	#{src}/tensorflow/core/framework/tensor.proto \
	#{src}/tensorflow/core/framework/resource_handle.proto \
	#{src}/tensorflow/core/framework/device_attributes.proto \
	#{src}/tensorflow/core/framework/allocation_description.proto \
	#{src}/tensorflow/core/example/feature.proto \
	#{src}/tensorflow/core/example/example_parser_configuration.proto \
	#{src}/tensorflow/core/example/example.proto \
	#{src}/tensorflow/core/lib/core/error_codes.proto \
	#{src}/tensorflow/core/protobuf/*.proto 
  CMD

  # Files generated by protoc
  s.subspec "Messages" do |ms|
    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
    ms.header_mappings_dir = dir
    ms.requires_arc = false
    # The generated files depend on the protobuf runtime.
    ms.dependency "Protobuf"
  end

  # Files generated by the gRPC plugin
  s.subspec "Services" do |ss|
    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
    ss.header_mappings_dir = dir
    ss.requires_arc = true
    # The generated files depend on the gRPC runtime, and on the files generated by protoc.
    ss.dependency "gRPC-ProtoRPC"
    ss.dependency "#{s.name}/Messages"
  end

  s.pod_target_xcconfig = {
    # This is needed by all pods that depend on Protobuf:
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    # This is needed by all pods that depend on gRPC-RxLibrary:
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
end
